name: Publish Any Commit
on: [push, pull_request]

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}

jobs:
  release:
    uses: sxzz/workflows/.github/workflows/release-commit.yml@v2.0.0
    with:
      compact: true
